dkpro/dkpro-cassis

cassis/cas.py, tests/test_cas.py
- Use XMI ID instead of sofaNum for token->sofa reference
=> #10 - Sofa key error

cassis/xmi.py, tests/test_xmi.py
- Only add the namespaces once
=> #19 - Fix CAS XMI namespaces

cassis/cas.py, cassis/typesystem.py, cassis/xmi.py, tests/fixtures.py, tests/test_cas.py, tests/test_files/xmi/cas_with_inheritance.xmi, tests/test_files/xmi/small_cas.xmi, tests/test_xmi.py
- Add sofa/view creating/getting
=> #5 - Add basic sofa/view support

cassis/cas.py, cassis/typesystem.py, cassis/xmi.py, tests/fixtures.py, tests/test_files/xmi/cas_with_string_array.xmi, tests/test_xmi.py
- Parse children of features in XMI
- Serialize string arrays as series of child elements
=> #39 - Add array support

cassis/cas.py, cassis/typesystem.py, cassis/xmi.py
- Change name were appropriate
=> #51 - Rename `Annotation` to `FeatureStructure`

.github/CONTRIBUTING.md, .github/CONTRIBUTORS.txt, cassis/__version__.py, setup.py, tests/test_cas.py
=> #58 - Release 0.2.0

cassis/typesystem.py, tests/fixtures.py, tests/test_files/typesystems/typesystem_with_redefined_documentannotation.xml, tests/test_typesystem.py
- Custom DocumentAnnotation can now be defined
=> #12 - Add proper DocumentMetaData support

README.rst
=> #69 - Document that you can change the typesystem after creating it

cassis/typesystem.py, tests/test_typesystem.py
- Warn when features are redefined identically
- Throw when features are redefined differently
=> #77 - ValueError when reading a type system file that redefines a feature

cassis/cas.py, tests/fixtures.py, tests/test_cas.py
- Add parsing capabilities for sofaUri
=> #79 - Error when reading XMI files with sofaURI

cassis/cas.py, cassis/typesystem.py, tests/test_cas.py, tests/test_typesystem.py, tests/test_xmi.py
- Exclude sofa from repr
- Add select_covering
=> #81 - Add more cas select methods

cassis/typesystem.py, cassis/xmi.py, tests/fixtures.py, tests/test_files/xmi/cas_with_collections.xmi, tests/test_typesystem.py
- Check that builtin collections are collections
=> #66 - Check more collections

README.rst, cassis/typesystem.py, tests/fixtures.py, tests/test_files/typesystems/typesystem_with_reserved_names.xml, tests/test_typesystem.py
- Issue warning when using feature called self
- Add README for that
=> #90 - Fails if contains features called self

cassis/xmi.py, tests/fixtures.py, tests/test_cas.py, tests/test_files/xmi/empty_cas.xmi
- Fix it for load_cas_from_xmi
=> #67 - Creating cas without typesystem shares the default typesystem

cassis/typesystem.py, tests/test_typesystem.py
- Check parents in `is_primitive`
=> #93 - Types extending primitive types are not considered primitive

README.rst, cassis/__init__.py, cassis/resources/dkpro-core-types.xml, cassis/typesystem.py, setup.py, tests/test_typesystem.py
- Add loader util for DKPro Core Type system
=> #9 - Add DKPro Typesystem support

README.rst, cassis/typesystem.py, cassis/xmi.py, tests/fixtures.py, tests/test_files/typesystems/typesystem_with_reserved_names.xml, tests/test_files/xmi/cas_with_reserved_names.xmi, tests/test_xmi.py
- Fix case for type
- Add more tests
=> #90 - XMI reading/writing fails if feature name is reserved

cassis/typesystem.py, cassis/xmi.py, tests/fixtures.py, tests/test_cas.py, tests/test_files/typesystems/typesystem_with_collections.xml, tests/test_files/xmi/cas_with_collections.xmi, tests/test_typesystem.py, tests/test_xmi.py
- Check if feature type or range type is stringarray or inherits from it
=> #100 - AttributeError while serializing CAS with stringarray inheritance

cassis/cas.py, cassis/xmi.py, tests/fixtures.py, tests/test_files/xmi/cas_with_nonindexed_fs.xmi, tests/test_files/xmi/cas_with_two_sofas.xmi, tests/test_xmi.py
- Collect fs from all views when serializing
- Generate new XMI ids for referenced fs
- Add test for CAS with two SOFAs
=> #102  - FS in other views not serialized

setup.py
=> #105 - Add package data to setup.py

README.rst, cassis/__init__.py, cassis/typesystem.py, tests/fixtures.py, tests/test_files/typesystems/typesystem_merge_base.xml, tests/test_typesystem.py
- Merging simple type systems
- Fix subsuming supertypes
- Add documentation
=> #108 - Add possibility to combine several type systems

cassis/xmi.py
- Create empty view for a sofa it is missing
=> #110 - UIMA allows different numbers of sofa and views but cassis does not

cassis/typesystem.py
=> #112 - Strip typesystem type names

cassis/cas.py, cassis/typesystem.py, cassis/xmi.py, tests/test_cas.py, tests/test_files/xmi/empty_cas.xmi, tests/test_xmi.py
We iterate over all indices of children and the type itself for all select methods now.
=> #104 - select_covered doesn't seem to work with base class

cassis/typesystem.py, cassis/xmi.py, tests/test_files/xmi/cas_with_collections.xmi, tests/test_xmi.py
=> #116 - Loading feature structures referencing NULL throws

setup.py
- Pin versions for all install dependencies
=> #118 - Pin dependency versions

README.rst, cassis/cas.py, cassis/typesystem.py, cassis/xmi.py, tests/test_cas.py, tests/test_typesystem.py
- Add typecheck method
- Add leniency
=> #25 - More type checking

cassis/cas.py, cassis/xmi.py, tests/test_files/xmi/cas_with_collections.xmi
=> #121 - XMI Serialization breaks Nested Feature Structures

cassis/typesystem.py
- Only create constructor on first access
=> #84 - Make creating type classes lazy

cassis/xmi.py, tests/test_files/xmi/cas_with_references.xmi
- Set sofa when loading from XMI
=> #133 - Resolve reference to sofa for nested FeatureStructure

Makefile, cassis/__init__.py, cassis/cas.py, cassis/typesystem.py, cassis/xmi.py, setup.py, tests/test_cas.py, tests/test_typesystem.py, tests/test_xmi.py, tests/util.py
You can now remove annotations
=> #138 - Add a "remove_annotation" method to the Cas object

README.rst, cassis/typesystem.py, cassis/xmi.py, tests/fixtures.py, tests/test_files/xmi/lenient_cas.xmi, tests/test_xmi.py
- Add leniency options to the xmi deserialize method.
=> #85 - Allow leniency to CAS deserialization

README.rst, cassis/typesystem.py, tests/test_files/typesystems/typesystem_with_inheritance.xml
- Add DocumentAnnotation before creating other types if it is not in the typesystem XML
=>  #142 - Cassis inheriting from DocumentAnnotation

cassis/cas.py, tests/test_cas.py
=> #144 - Overlapping annotations not selected with select_covered

cassis/cas.py, tests/test_cas.py
I do not like needing to use list(cas.select..) on everything, so we remove iterators and return lists
=> #147 - Remove iterators

README.rst, cassis/xmi.py
=> #153 - Load large XMI files

cassis/xmi.py, tests/test_files/xmi/small_cas.xmi, tests/test_xmi.py
- Set xmiId of initial sofa when loading from XMI
=> #155 - xmiId of initial sofa is wrong

cassis/typesystem.py, cassis/xmi.py
=> #163 - XMI output encoding is ASCII instead of UTF-8

cassis/typesystem.py, tests/test_typesystem.py
- Added better error message printing the bad path and the FS
- Added test
=> #183 - Better error message when failing to resolve feature path

cassis/xmi.py, tests/test_files/typesystems/typesystem_with_collections.xml, tests/test_files/xmi/cas_with_collections.xmi
- Handle empty arrays during XMI (de)serialization
- Handle array features where actually no target array exists
- Upgraded tests to include empty and non-existing arrays
=> #211 - Serializing an FSArray without any elements breaks

cassis/typesystem.py, cassis/xmi.py
- Allow  loading CAS or type system by specifying a Path
=> #212 - Allow loading/saving XMI/typesystems from/to Path

cassis/util.py, tests/test_util.py
- Added exclude_types parameter
- Added test
=> #215 - Ability to exclude types from cas_to_comparable_text

cassis/xmi.py, tests/test_files/xmi/cas_with_collections.xmi
- Fixed issue
- Added test case
=> #221 - Unable to parse empty arrays

setup.py, tests/test_documentation.py
- Wrote unit test to check rst
=> #225 - Add check for properly formatted README.rst

cassis/util.py
=> #231 - cas_to_comparable_text breaks saying that FSes do not have an ID

cassis/typesystem.py
- Add __str__ to type and feature
=> #236 - Long output when printing type

cassis/cas.py, cassis/typesystem.py, tests/test_typesystem.py
Write custom repr instead of generating as it otherwise recursively prints too much stuff
=> #252 - Better repr for typs, feature structures and Sofas

README.rst
A very simple typo in the word "enriched".
=> Fixed a typo in README

cassis/json.py, tests/test_json.py
- First load types then features to resolve recursive type definitions
=> #265 - Error parsing certain JSONs with embedded type system

cassis/typesystem.py, cassis/xmi.py, tests/test_typesystem.py
- Post-process merged type system to ensure internal consistency
- Unit test checking for consistency of merged type system
- Auto-format
=> #270 - Merging type systems breaks consistency

.readthedocs.yml, cassis/cas.py, tests/test_cas.py, tests/test_json.py, tests/test_typesystem.py
- Accept type name or type in selects
- Updated tests
=> #217 - Use types in selects

cassis/typesystem.py
=> #295 - Improve warning message in _add_feature()

cassis/typesystem.py, cassis/xmi.py, tests/test_cas.py, tests/test_json.py, tests/test_typesystem.py
- Change some references to types to use constants
=> #301 - Make better use of type constants in code

.github/ISSUE_TEMPLATE/refactoring.md, setup.py
- Relax the version
- Add refactoring issue template
=> #305 - Relax version constraints on itertools

cassis/typesystem.py, tests/test_typesystem.py
**What's in the PR**
- Implement iter method in type system
**How to test manually**
* See issue description
**Automatic testing**
**Documentation**
=> #308 - Make type system iterable

cassis/typesystem.py, pyproject.toml, tests/test_documentation.py, tests/test_typesystem.py, tests/test_util.py, tests/test_xmi.py
**What's in the PR**
- Fixed issue and added test
**How to test manually**
* See issue description
**Automatic testing**
**Documentation**
=> #322 - Error that type already exists during typesystem load
