dkpro/dkpro-cassis

- cassis/cas.py
- cassis/xmi.py
- tests/test_xmi.py
- When serializing XMI, construct tree in memory first, then clean namespaces, then write it at once. Before it was written incrementally
- Remove namespaces member from Cas object
> #19 - Fix CAS XMI namespace serialization

- cassis/xmi.py
- tests/test_xmi.py
- When two different types would get the same prefix during XMI
serialization, add a numerical suffix
> #19 - Disambiguate CAS XMI namespace

- cassis/xmi.py
- tests/fixtures.py
- tests/test_files/xmi/cas_with_nonindexed_fs.xmi
- tests/test_xmi.py
- Instead of using select_all when serializing XMI, traverse the Cas to find all the feature structures, also indirect ones
> #64 - Reading xmi then writing again results in broken xmi file

- cassis/typesystem.py
- cassis/xmi.py
- setup.py
- tests/fixtures.py
- tests/test_files/xmi/cas_with_empty_array_reference.xmi
- tests/test_xmi.py
- Add None check when traversing CAS for serialising
- Add tests
- Fix deprecation warning of attrs
> #70 - XMI serialising throws if CAS contains reference to empty array

- cassis/cas.py
- tests/test_cas.py
- Use none instead of inline construction of default parameter
> #67 - Creating cas without typesystem shares the default typesystem

- README.rst
- cassis/cas.py
- cassis/typesystem.py
- cassis/xmi.py
- setup.py
- tests/fixtures.py
- tests/test_cas.py
- Make annotation.sofa an actual reference to the sofa instead of just storing its XMI ID
- During serialization, fetch the XMI ID and write it out
> #73 - Add get_covered_text method to Annotations

- cassis/typesystem.py
- tests/test_cas.py
- tests/test_files/typesystems/typesystem_has_types_with_no_namespace.xml
- Add prefix to supertype in case of missing namespace
- Remove prefix on save
- Fix covered_text deprecation warning
> #88 - Keyerror if supertype has no namespace

- cassis/typesystem.py
- tests/test_files/typesystems/small_typesystem.xml
- tests/test_typesystem.py
- Use real logic to parse bools
>  #157 - String in multipleReferencesAllowed is incorrectly parsed

- cassis/typesystem.py
- cassis/xmi.py
- tests/test_files/xmi/cas_with_collections.xmi
- tests/test_typesystem.py
Turns out that there was no support for primitive array serialization/deserialization at all
> #167 - Cant serialize byte arrays

- README.rst
- cassis/typesystem.py
- tests/test_typesystem.py
- Add create_feature
- Deprecate add_feature
> #173 - Rename add_feature to create_feature

- cassis/typesystem.py
- cassis/xmi.py
- tests/fixtures.py
- tests/test_files/typesystems/typesystem_has_types_with_no_namespace.xml
- tests/test_files/xmi/cas_has_fs_with_no_namespace.xmi
- tests/test_xmi.py
- Move no namespace handling to xmi
- Add better tests for this
> #170 - Handling of the "uima.noNamespace" prefix

- cassis/xmi.py
- tests/test_xmi.py
- When serializing XMI, set XMI ids if None
> #174 - FSes that are only transitively referenced cannot be serialized

- README.rst
- cassis/typesystem.py
- tests/test_typesystem.py
>  #175 - Set a feature if the feature name is in a variable

- README.rst
- cassis/cas.py
- cassis/xmi.py
- tests/fixtures.py
- tests/test_cas.py
- tests/test_typesystem.py
- tests/test_xmi.py
- cas.add_annotations -> cas.add
> #172 - Naming: cas.add_annotation(s)

- cassis/cas.py
- cassis/xmi.py
- tests/test_cas.py
- tests/test_xmi.py
- Initial fix did only work for the first fs without xmiID, but as soon as there would be two FSes with missing ids, it broke
- Extended the test
- Implemented an alternative fix that optionally sets the missing IDs while scanning the CAS for FSes thus also avoiding scanning the CAS twice during serialization
> #174 - FSes that are only transitively referenced cannot be serialized (#179)

- cassis/cas.py
- cassis/typesystem.py
- cassis/xmi.py
- tests/test_cas.py
- tests/test_files/typesystems/typesystem_with_collections.xml
- tests/test_files/xmi/cas_with_collections.xmi
- tests/test_typesystem.py
- tests/test_xmi.py
#185 - Transitively referenced primitive arrays not returned by _find_all_fs
#186 - Creating subtypes of inheritance-final types (arrays) is not prevented
#187 - The multipleReferencesAllowed flag on array features is not handled
- Consistently wrap arrays into their proper UIMA array types when deserializing
- Tests and code updated because in order to access the array elements it is now necessary to access them via the `elements` property of the array wrapper
- Add handling of the multipleReferencesAllowed flag in during (de)serialization
> #185 #186 #187: Handling of multipleReferencesAllowed and arrays

- cassis/xmi.py
- tests/fixtures.py
- tests/test_files/typesystems/typesystem_with_multiple_references_allowed.xml
- tests/test_files/xmi/cas_with_multiple_references_allowed_string_array.xmi
- tests/test_xmi.py
- Fixed problem by checking the multipleReferencesAllowed feature during deserialization
- Added test
> #209 - Parsing an array that was serialized using multipleReferencesAllowed=true fails

- cassis/cas.py
- None is a valid value for the offset mapping
- If the mapping is none, then do not try to map
> #227 - If a CAS contains no text the offset mapping initialization fails

- cassis/typesystem.py
- tests/test_typesystem.py
- Added utility method
- Added test
- Modernize tests
> #229 - Get transitive closure of types

- cassis/util.py
- tests/test_util.py
- Fixed issue
- Added test case
> #234 - cas_to_comparable_text fails with null arrays

- cassis/cas.py
- cassis/json.py
- cassis/xmi.py
- tests/test_xmi.py
- Rename offset converter class
- If an offset is invalid according to the mapping strategy, do not map it - pass through as is and log warning
- Added test that invalid offsets are passed through on import and export and that warnings are logged
> #162 - Handling of Invalid sofa indexes

- cassis/typesystem.py
We now do not warn when redefining features during merge, as that leads too many warnings, especially when merging very similar type systems.
> #253 - Do not emit warnings during merge

- .github/workflows/publish_to_pypi.yml
- .github/workflows/run_tests.yml
- setup.py
- Try upgrading to newer python setup action
> #268 - GitHub Actions builds do not run due to missing Python version

- cassis/xmi.py
Closing #266 .
During deserialization, we construct a small map that holds the information if a given type inherit from STRING_ARRAY.
> Issue #266: Caching typesystem.is_instance_of(..., TYPE_NAME_STRING_ARRAY)

- cassis/json.py
- cassis/typesystem.py
- tests/test_files/json/child_type_before_parent.json
- tests/test_json.py
- tests/test_typesystem.py
- Add is_predefined helper
- Use toposort to fix the bug
> #276 - Cannot deserialize from JSON Cas if child type comes before super type

- cassis/json.py
- tests/test_files/json/fs_as_array/one-way/casWithBadSofaFsOrder/data-ref.json
- tests/test_files/json/fs_as_array/one-way/casWithBadSofaFsOrder/data.json
- tests/test_json.py
- Fix issue by iterating twice over the FS list, once for Sofas and once for other FSes
- Added test case
> #283 - Allow reading JSON CASes with out-of-order SofaFSes

- cassis/cas.py
- cassis/xmi.py
1. Added an LRU Cache for speeding up the `encode` function and refactored the `create_offset_mapping`
2. When reading a CAS-XMI, directly pass down the offset mappings to avoid recomputing them.
Reduced the time spent in `create_offset_mapping` from 49% to 8%.
> #290 - Speedup load_cas_from_xmi by improving offset mapping

- cassis/json.py
- Add lenient loading parameter when loading CAS from JSON
- Add merge_typesystem parameter when loading CAS from JSON
> Add lenient loading and type system merging to load_cas_from_json

- tests/test_cas.py
- Remove redundant and unsed CAS declaration
> #297 - Possible inconsistency in test fixtures

- cassis/typesystem.py
- tests/test_cas.py
- Fix problem that the TOP type never gets any child types assigned despite it being the root type
- Added unit test
> #299 - cassis won't find tokens when doing cas.select(...TOP)

- cassis/cas.py
- cassis/json.py
- cassis/typesystem.py
- tests/test_cas.py
- tests/test_json.py
- tests/test_typesystem.py
- Added constructor arguments
- Added test
> #249 - Set sofa string and document language in Cas constructor

- README.rst
- cassis/cas.py
- tests/test_cas.py
- tests/test_documentation.py
- Added get_document_annotation()
- Added document_language property
- Added test
> #250 - Convenience for setting the document language

- cassis/typesystem.py
- tests/test_typesystem.py
**What's in the PR**
- Added the property and a test
**How to test manually**
* No specific test procedure
**Automatic testing**
**Documentation**
> #310 - Add short_name property to type

- cassis/cas.py
- cassis/json.py
- cassis/xmi.py
- tests/test_cas.py
- tests/test_json.py
- tests/test_typesystem.py
- tests/test_util.py
- tests/test_xmi.py
**What's in the PR**
- Fix duplicate method name
- Address linter issues
- Formatting
**How to test manually**
* No specific test procedure
**Automatic testing**
**Documentation**
> #318 - Address linter issues
